### ISSUE TITLE
ModuleNotFoundError: No module named 'nsfr.common'

### ISSUE THREAD

**Issue by Tianming40** [k4ntz/NUDGE#7]
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    from nudge.agents.logic_agent import LogicPPO
  File "/mnt/d/UNI/NUDGE/nudge/agents/logic_agent.py", line 10, in <module>
    from nsfr.common import get_nsfr_model
ModuleNotFoundError: No module named 'nsfr.common'

**Comment by Tianming40** [comment]
Unter dem NSFR-Ordner befindet sich immer noch ein Ordner namens nsfr, der Importprobleme verursacht？

**Comment by k4ntz** [comment]
Hi there, have you installed the nsfr module using:
`pip install -e .` from the nsfr folder ?

**Comment by Tianming40** [comment]
hi, Thank you for your reply. I just tried Quickstart in the README. The installation in requirement.txt was successful, but when I run train.py, it prompts that nfsr cannot be found. When I try `pip install -e .` in the NAGUE folder, the following error will occur.
```(NUDGE) ming@LAPTOP-EMOK5QV6:/mnt/d/UNI/NUDGE$ pip install -e .
Obtaining file:///mnt/d/UNI/NUDGE
ERROR: file:///mnt/d/UNI/NUDGE does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

Best regards,
Ming

**Comment by k4ntz** [comment]
You need to install from the nsfr project.
You need to do:
`cd nsfr` before `pip install -e .`

**Comment by Tianming40** [comment]
It works now, thank you very much 👍
